const tabs=['Dashboard','Pratica','Impianto','Frutti e materiali','Quadri e circuiti','Livello CEI','Verifiche','Allegati','Unifilare','Fascicolo'];
const YEAR=new Date().getFullYear();
const emptyState=(no)=>({practiceNo:no||nextNo(),doc:'Di.Co.',status:'In lavorazione',client:'',clientTax:'',clientPhone:'',clientEmail:'',address:'',city:'',province:'',work:'Nuovo impianto',workDescription:'',use:'Residenziale',phase:'Monofase',voltage:'230 V',power:'6',earth:'TT',level:'1',brand:'',series:'',fruits:[],circuits:[],checks:{},attachments:[],company:'Vimer Tek Srls',technician:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
function archive(){try{return JSON.parse(localStorage.getItem('vt_dico_archive')||'[]')}catch{return[]}}
function nextNo(){let a=archive(), nums=a.map(p=>+(String(p.practiceNo||'').match(/(\d+)$/)||[])[1]||0);return `VT-DICO-${YEAR}-${String(Math.max(0,...nums)+1).padStart(3,'0')}`}
let state;try{state=JSON.parse(localStorage.getItem('vt_dico')||'null')}catch{}; state=state||emptyState(); let active=0;
const help=t=>`<span class='help' title='${t.replaceAll("'","&#39;")}'>?</span>`; const field=(k,l,h,type='text')=>`<label>${l}${help(h)}<input type='${type}' data-k='${k}' value='${escAttr(state[k]||'')}'></label>`;
function nav(){document.querySelector('#nav').innerHTML=tabs.map((x,i)=>`<button data-tab='${i}' class='${i===active?'active':''}'>${x}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{active=+b.dataset.tab;render()})}
function dashboard(){let a=archive();return `<div class=grid3><div class=card><div class=muted>Pratica corrente</div><div class=stat>${esc(state.practiceNo)}</div></div><div class=card><div class=muted>Pratiche archiviate</div><div class=stat>${a.length}</div></div><div class=card><div class=muted>Stato</div><div class=stat smallstat>${esc(state.status||'In lavorazione')}</div></div></div><div class=card><h2>Gestione pratiche</h2><p>Crea, salva, riapri e modifica le pratiche Di.Co./Di.Ri. I dati tecnici vengono riutilizzati nelle sezioni successive.</p><div class=row><button onclick='newPractice()'>+ Nuova pratica</button><button class=secondary onclick='showArchive()'>Archivio pratiche</button></div></div><div id=archiveBox>${archiveHtml(a)}</div>`}
function archiveHtml(a){if(!a.length)return '';return `<div class=card><h2>Ultime pratiche</h2><div class=archive-list>${a.slice().reverse().slice(0,8).map(p=>`<div class=archive-item><div><b>${esc(p.practiceNo)}</b><br><span>${esc(p.client||'Cliente da definire')} · ${esc(p.doc||'Di.Co.')}</span><br><small>${esc(p.address||p.city||'Ubicazione da definire')}</small></div><div><span class=pill>${esc(p.status||'In lavorazione')}</span><button onclick="openPractice('${escAttr(p.practiceNo)}')">Apri</button></div></div>`).join('')}</div></div>`}
function showArchive(){document.querySelector('#archiveBox').innerHTML=archiveHtml(archive())||`<div class=card>Nessuna pratica archiviata.</div>`}
function pratica(){return `<div class=card><h2>Dati pratica</h2><div class=grid>${field('practiceNo','Numero pratica','Identificativo univoco della pratica.')}<label>Documento ${help('Seleziona Di.Co. o Di.Ri.')}<select data-k=doc>${['Di.Co.','Di.Ri.'].map(x=>`<option ${state.doc===x?'selected':''}>${x}</option>`)}</select></label><label>Stato<select data-k=status>${['In lavorazione','Da verificare','Completata'].map(x=>`<option ${state.status===x?'selected':''}>${x}</option>`)}</select></label>${field('client','Cliente / committente','Intestatario o committente dei lavori.')}${field('clientTax','Codice fiscale / P.IVA','Dato fiscale del cliente o committente.')}${field('clientPhone','Telefono','Recapito telefonico del cliente.','tel')}${field('clientEmail','Email','Email del cliente.','email')}${field('address','Ubicazione impianto','Via/piazza e numero civico.')}${field('city','Comune','Comune dell’impianto.')}${field('province','Provincia','Sigla provincia.')}<label>Intervento<select data-k=work>${['Nuovo impianto','Trasformazione','Ampliamento','Manutenzione straordinaria','Altro'].map(x=>`<option ${state.work===x?'selected':''}>${x}</option>`)}</select></label><label>Destinazione<select data-k=use>${['Residenziale','Commerciale','Artigianale','Industriale','Uffici','Altro'].map(x=>`<option ${state.use===x?'selected':''}>${x}</option>`)}</select></label><label class=wide>Descrizione lavori<textarea data-k=workDescription>${esc(state.workDescription||'')}</textarea></label>${field('company','Impresa esecutrice','Impresa che rilascia la dichiarazione.')}${field('technician','Responsabile tecnico','Nome e cognome del responsabile tecnico.')}</div><div class=actions><button onclick='save(true)'>Salva pratica</button><button class=secondary onclick='active=2;render()'>Continua → Impianto</button></div></div>`}
function impianto(){return `<div class=card><h2>Caratteristiche impianto</h2><div class=grid><label>Sistema<select data-k=phase>${['Monofase','Trifase'].map(x=>`<option ${state.phase===x?'selected':''}>${x}</option>`)}</select></label>${field('voltage','Tensione','Tensione nominale.')}${field('power','Potenza (kW)','Potenza disponibile/impegnata.','number')}${field('earth','Sistema di distribuzione','Es. TT, TN-S, TN-C-S, IT.')}</div></div>`}
function materials(){let rows=state.fruits.map((x,i)=>`<tr><td>${esc(x.room)}</td><td>${esc(x.brand)}</td><td>${esc(x.series)}</td><td>${esc(x.type)}</td><td>${x.qty}</td><td><button onclick='delFruit(${i})'>×</button></td></tr>`).join('');return `<div class=card><h2>Frutti e punti impianto</h2><div class=grid>${field('brand','Marca predefinita','Marca serie civile.')}${field('series','Serie predefinita','Serie civile.')}</div><hr><div class=grid3><input id=froom placeholder='Locale'><input id=ftype placeholder='Tipo frutto'><input id=fqty type=number min=1 value=1></div><button onclick='addFruit()'>+ Aggiungi frutto</button></div><div class=card><table class=table><tr><th>Locale</th><th>Marca</th><th>Serie</th><th>Tipologia</th><th>Qtà</th><th></th></tr>${rows||'<tr><td colspan=6>Nessun elemento</td></tr>'}</table></div>`}
function circuits(){let rows=state.circuits.map((x,i)=>`<tr><td>${esc(x.name)}</td><td>${esc(x.prot)}</td><td>${esc(x.cable)}</td><td>${esc(x.dest)}</td><td><button onclick='delCircuit(${i})'>×</button></td></tr>`).join('');return `<div class=card><h2>Quadri e circuiti</h2><div class=grid><input id=cname placeholder='Sigla / nome circuito'><input id=cprot placeholder='Protezione es. MT C16 1P+N'><input id=ccable placeholder='Cavo es. FG16 3G2,5'><input id=cdest placeholder='Destinazione'></div><button onclick='addCircuit()'>+ Aggiungi circuito</button></div><div class=card><table class=table><tr><th>Circuito</th><th>Protezione</th><th>Cavo</th><th>Destinazione</th><th></th></tr>${rows||'<tr><td colspan=5>Nessun circuito</td></tr>'}</table></div>`}
function level(){return `<div class=card><h2>Livello impianto residenziale</h2><label>Livello dichiarato<select data-k=level>${['1','2','3'].map(x=>`<option ${state.level===x?'selected':''}>Livello ${x}</option>`)}</select></label><div class=box><b>Dati disponibili:</b><br>Frutti: ${state.fruits.reduce((a,x)=>a+(+x.qty||0),0)}<br>Circuiti: ${state.circuits.length}<br>Potenza: ${state.power||'-'} kW</div></div>`}
function checks(){let names=['Esame a vista','Continuità PE/equipotenziali','Resistenza di isolamento','Protezione mediante interruzione automatica','Prova differenziali','Polarità','Prove funzionali'];return `<div class=card><h2>Verifiche</h2>${names.map((x,i)=>`<label class=checkrow><input type=checkbox data-check='${i}' ${state.checks[i]?'checked':''}> ${x}</label>`).join('')}${field('instrument','Strumento di misura','Marca/modello.')}${field('serial','Matricola strumento','Numero di serie.')}</div>`}
function attachments(){return `<div class=card><h2>Allegati</h2><p class=muted>Puoi selezionare più file contemporaneamente. In questa versione locale vengono memorizzati i nomi dei file nella pratica.</p><input id=files type=file multiple><button onclick='addFiles()'>Aggiungi</button><div>${state.attachments.map((x,i)=>`<span class=pill>${esc(x)} <b onclick='delFile(${i})'>×</b></span>`).join('')}</div></div>`}
function unifilar(){let h=Math.max(350,130+state.circuits.length*85),lines=state.circuits.map((c,i)=>{let y=125+i*80;return `<line x1='130' y1='${y}' x2='310' y2='${y}' stroke='black' stroke-width='2'/><rect x='310' y='${y-22}' width='190' height='44' fill='white' stroke='black'/><text x='320' y='${y-5}' font-size='13'>${esc(c.name)} — ${esc(c.prot)}</text><text x='320' y='${y+13}' font-size='11'>${esc(c.cable)} → ${esc(c.dest)}</text>`}).join('');return `<div class=card><h2>Schema unifilare automatico</h2><div class=unifilar><svg width='850' height='${h}'><text x='30' y='30' font-size='18' font-weight='bold'>${esc(state.practiceNo)}</text><rect x='30' y='65' width='100' height='55' fill='white' stroke='black'/><text x='45' y='88' font-size='12'>RETE</text><text x='42' y='105' font-size='11'>${esc(state.phase)} ${esc(state.voltage)}</text><line x1='80' y1='120' x2='80' y2='${110+state.circuits.length*80}' stroke='black' stroke-width='3'/>${lines}</svg></div></div>`}
function fascicolo(){return `<div class=card><div class=cover><img src='assets/logo-vimertek.png'><h2>FASCICOLO TECNICO IMPIANTO ELETTRICO</h2><h3>${esc(state.doc)}</h3><div>${esc(state.practiceNo)}</div><div class=box><b>Cliente:</b> ${esc(state.client||'—')}<br><b>Ubicazione:</b> ${esc([state.address,state.city,state.province].filter(Boolean).join(', ')||'—')}<br><b>Intervento:</b> ${esc(state.work)}<br><b>Destinazione:</b> ${esc(state.use)}<br><b>Impresa:</b> ${esc(state.company||'—')}<br><b>Responsabile tecnico:</b> ${esc(state.technician||'—')}</div></div></div><div class=card><button onclick='window.print()'>Anteprima / stampa browser</button></div>`}
function render(){nav();document.querySelector('#app').innerHTML=[dashboard,pratica,impianto,materials,circuits,level,checks,attachments,unifilar,fascicolo][active]();bind()}
function bind(){document.querySelectorAll('[data-k]').forEach(e=>{let ev=e.tagName==='TEXTAREA'?'input':'change';e.addEventListener(ev,()=>{state[e.dataset.k]=e.value;save(false)})});document.querySelectorAll('[data-check]').forEach(e=>e.onchange=()=>{state.checks[e.dataset.check]=e.checked;save(false)})}
function save(msg=true){state.updatedAt=new Date().toISOString();localStorage.setItem('vt_dico',JSON.stringify(state));let a=archive(),i=a.findIndex(p=>p.practiceNo===state.practiceNo);if(i>=0)a[i]=JSON.parse(JSON.stringify(state));else a.push(JSON.parse(JSON.stringify(state)));localStorage.setItem('vt_dico_archive',JSON.stringify(a));if(msg)alert('Pratica salvata e archiviata sul dispositivo.')}
function newPractice(){if(!confirm('Creare una nuova pratica? La pratica corrente verrà salvata.'))return;save(false);state=emptyState();localStorage.setItem('vt_dico',JSON.stringify(state));active=1;render()}
function openPractice(no){let p=archive().find(x=>x.practiceNo===no);if(!p)return;state=p;localStorage.setItem('vt_dico',JSON.stringify(state));active=1;render()}
function addFruit(){if(!ftype.value.trim()||!+fqty.value)return;state.fruits.push({room:froom.value.trim(),brand:state.brand||'Da definire',series:state.series||'Da definire',type:ftype.value.trim(),qty:+fqty.value});save(false);render()} function delFruit(i){state.fruits.splice(i,1);save(false);render()}
function addCircuit(){if(!cname.value.trim())return;state.circuits.push({name:cname.value,prot:cprot.value,cable:ccable.value,dest:cdest.value});save(false);render()} function delCircuit(i){state.circuits.splice(i,1);save(false);render()}
function addFiles(){[...files.files].forEach(f=>{if(!state.attachments.includes(f.name))state.attachments.push(f.name)});save(false);render()} function delFile(i){state.attachments.splice(i,1);save(false);render()}
function esc(s=''){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))} function escAttr(s=''){return esc(s).replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
document.querySelector('#save').onclick=()=>save(); render();
